import { Router } from "express";
import type { Request, Response } from "express";
import jwt from "jsonwebtoken";
import supabase from "../config/supabaseClient";

const router = Router();

// --- User Registration ---
router.post('/register', async (req: Request, res: Response) => {
  const { email, password } = req.body;

  if (!email || !password) {
    return res.status(400).json({ error: 'Email and password are required.' });
  }

  // 1. Create the user in Supabase Auth
  const { data: authData, error: authError } = await supabase.auth.signUp({
    email,
    password,
  });

  if (authError) {
    return res.status(400).json({ error: authError.message });
  }

  // Type guard to ensure the user object exists
  if (!authData.user) {
    return res.status(500).json({ error: 'User could not be created.' });
  }

  // --- 2. THIS BLOCK IS NOW REMOVED ---
  // The database trigger 'on_auth_user_created'
  // handles this automatically.
  /*
  const { error: profileError } = await supabase
    .from('profiles')
    .insert({
      id: authData.user.id,
      email: email,
      role: 'user'
    });

  if (profileError) {
    return res.status(500).json({ error: profileError.message });
  }
  */

  res.status(201).json({ message: 'User registered. Please check your email to verify.' });
});


// --- User & Admin Login ---
router.post('/login', async (req: Request, res: Response) => {
  // ... existing code ...
  const { email, password } = req.body;

  // ... existing code ...
  if (!email || !password) {
    // ... existing code ...
    return res.status(400).json({ error: 'Email and password are required.' });
    // ... existing code ...
  }

  // ... existing code ...
  // 1. Authenticate user with Supabase Auth
  // ... existing code ...
  const { data: authData, error: authError } = await supabase.auth.signInWithPassword({
    // ... existing code ...
    email,
    // ... existing code ...
    password,
    // ... existing code ...
  });

  // ... existing code ...
  if (authError) {
    // ... existing code ...
    return res.status(400).json({ error: authError.message });
    // ... existing code ...
  }

  // ... existing code ...
  // Type guard to ensure the user object exists
  // ... existing code ...
  if (!authData.user) {
    // ... existing code ...
    return res.status(400).json({ error: 'Login failed, user data not found.' });
    // ... existing code ...
  }

  // ... existing code ...
  // 2. Fetch the user's profile to get their role
  // ... existing code ...
  const { data: profileData, error: profileError } = await supabase
    // ... existing code ...
    .from('profiles')
    // ... existing code ...
    .select('role')
    // ... existing code ...
    .eq('id', authData.user.id)
    // ... existing code ...
    .single();

  // ... existing code ...
  if (profileError || !profileData) {
    // ... existing code ...
    return res.status(404).json({ error: 'User profile not found.' });
    // ... existing code ...
  }

  // ... existing code ...
  // Check for the JWT secret before using it
  // ... existing code ...
  if (!process.env.JWT_SECRET) {
    // ... existing code ...
    console.error('JWT_SECRET is not defined in environment variables.');
    // ... existing code ...
    return res.status(500).json({ error: 'Internal server error: Server is not configured correctly.' });
    // ... existing code ...
  }

  // ... existing code ...
  // 3. Create a JWT
  // ... existing code ...
  const token = jwt.sign(
    // ... existing code ...
    {
      // ... existing code ...
      id: authData.user.id,
      // ... existing code ...
      email: authData.user.email,
      // ... existing code ...
      role: profileData.role // This is the crucial part
      // ... existing code ...
    },
    // ... existing code ...
    process.env.JWT_SECRET,
    // ... existing code ...
    { expiresIn: '1d' } // Token expires in 1 day
    // ... existing code ...
  );

  // ... existing code ...
  res.json({
    // ... existing code ...
    message: 'Login successful',
    // ... existing code ...
    token,
    // ... existing code ...
    user: {
      // ... existing code ...
      id: authData.user.id,
      // ... existing code ...
      email: authData.user.email,
      // ... existing code ...
      role: profileData.role
      // ... existing code ...
    }
    // ... existing code ...
  });
  // ... existing code ...
});

export default router;
